In [2]:
import numpy as np
from scipy import linalg

In [27]:
def commutator(A, B):
    return np.dot(A, B) - np.dot(B, A)

def anticommutator(A, B):
    return np.dot(A, B) + np.dot(B, A)

In [36]:
Sx = np.array([[ 0,  0,  1],
               [ 0,  0,  0],
               [-1,  0,  0]])

Sy = np.array([[ 0, -1,  0],
               [ 1,  0,  0],
               [ 0,  0,  0]])

Sz = np.array([[ 0,  0,  0],
               [ 0,  0,  1],
               [ 0, -1,  0]])

print(commutator(Sx, Sy) - Sz)
print(commutator(Sy, Sz) - Sx)
print(commutator(Sz, Sx) - Sy)

[[ 0  0  0]
 [ 0  0 -2]
 [ 0  2  0]]
[[ 0  0 -2]
 [ 0  0  0]
 [ 2  0  0]]
[[ 0  2  0]
 [-2  0  0]
 [ 0  0  0]]


In [35]:
Sx = np.array([[ 0, -1,  0],
               [ 1,  0,  0],
               [ 0,  0,  0]])

Sy = np.array([[ 0,  0, -1],
               [ 0,  0,  0],
               [ 1,  0,  0]])

Sz = np.array([[ 0,  0,  0],
               [ 0,  0, -1],
               [ 0,  1,  0]])

print(commutator(Sx, Sy) - Sz)
print(commutator(Sy, Sz) - Sx)
print(commutator(Sz, Sx) - Sy)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
M = np.array([[ 1,  1],
              [ 0,  1]])

In [7]:
(eigvals, eigvecs) = linalg.eig(M)
eigvecs = np.transpose(eigvecs)

In [8]:
print(eigvals)
for eigvec in eigvecs:
    print(eigvec)

[1.+0.j 1.+0.j]
[1. 0.]
[-1.00000000e+00  2.22044605e-16]


In [51]:
U = np.array([[                            1,                             1],
              [(np.sqrt(2) + np.sqrt(6)) / 2, (np.sqrt(2) - np.sqrt(6)) / 2]]) 

In [47]:
np.dot(np.dot(np.transpose(U), M), U)

array([[  8.19615242e+00,   6.66133815e-16],
       [  4.44089210e-16,  -2.19615242e+00]])

In [48]:
np.dot(np.dot(U, M), np.transpose(U))

array([[ 2.82842712, -0.44948974],
       [-0.44948974, -6.29252874]])

In [56]:
np.dot(np.transpose(U), U)

array([[  4.73205081e+00,   4.44089210e-16],
       [  4.44089210e-16,   1.26794919e+00]])

In [61]:
W = np.array([[                            1 / np.sqrt(3 + np.sqrt(3)),                             1 / np.sqrt(3 - np.sqrt(3))],
              [(np.sqrt(2) + np.sqrt(6)) / (2*np.sqrt(3 + np.sqrt(3))), (np.sqrt(2) - np.sqrt(6)) / (2*np.sqrt(3 - np.sqrt(3)))]])

In [63]:
np.dot(W, np.transpose(W))

array([[  1.00000000e+00,   2.22044605e-16],
       [  2.22044605e-16,   1.00000000e+00]])

In [65]:
np.dot(np.dot(W, M), np.transpose(W))

array([[  1.73205081e+00,   3.33066907e-16],
       [  3.33066907e-16,  -1.73205081e+00]])

In [66]:
D = np.array([[ np.sqrt(3),          0],
              [         0, -np.sqrt(3)]])

In [67]:
np.dot(np.dot(W, D), np.transpose(W))

array([[-1.        ,  1.41421356],
       [ 1.41421356,  1.        ]])

In [68]:
np.dot(np.dot(np.transpose(W), D), W)

array([[-1.        ,  1.41421356],
       [ 1.41421356,  1.        ]])

In [2]:
t = np.sqrt(2)

In [5]:
U = np.array([[ 0.5,  0.5,  1/t,    0],
              [ 0.5, -0.5,    0,  1/t],
              [ 0.5,  0.5, -1/t,    0],
              [ 0.5, -0.5,    0, -1/t]])

In [6]:
U_I = linalg.inv(U)
print(U_I)

[[ 0.5         0.5         0.5         0.5       ]
 [ 0.5        -0.5         0.5        -0.5       ]
 [ 0.70710678  0.         -0.70710678 -0.        ]
 [ 0.          0.70710678  0.         -0.70710678]]
